// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://navnadoeznbzvqivamem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hdm5hZG9lem5ienZxaXZhbWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTc3NzUsImV4cCI6MjA2NzQ3Mzc3NX0.O5UsGLAEVnwZGhzYjg4ePCWgz1qEiLBSfqDKRGV4kME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});